# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/extra-cmake-modules': '@stable'
    'frameworks/kcoreaddons': '@stable'
    'frameworks/kconfig': '@stable'
    'frameworks/ki18n': '@stable'
    'frameworks/kirigami': '@stable'
    'frameworks/kio': '@stable'
    'frameworks/kdeclarative': '@stable'
    'frameworks/kguiaddons': '@stable'
    'frameworks/knotifications': '@stable'
    'frameworks/kfilemetadata': '@stable'
    'frameworks/kdbusaddons': '@stable'
    'libraries/kquickimageeditor': '@stable'
